# Generated by Django 4.0.2 on 2022-02-26 18:36

from django.db import migrations, models
import expense_tracker.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='images/user.png', upload_to='images', validators=[expense_tracker.validators.ValidateMaxSizeImage(5)]),
        ),
    ]
